-- USERS TABLE - Authentication and Role Management
CREATE TABLE users (
    user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) UNIQUE NOT NULL,
    password        VARCHAR2(255) NOT NULL,
    role            VARCHAR2(30) NOT NULL CHECK (role IN ('admin', 'inflightStaff', 'checkinStaff', 'passenger')),
    name            VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100),
    phone_number    VARCHAR2(20),
    flight_id       NUMBER,  -- For staff members assigned to specific flights
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_login      TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_role ON users(role);