-- FLIGHTS TABLE
CREATE TABLE flights (
    flight_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_name         VARCHAR2(50) NOT NULL,
    flight_date         DATE NOT NULL,
    route               VARCHAR2(20) NOT NULL,  -- e.g., 'NYC-LON'
    departure_time      VARCHAR2(20) NOT NULL,  -- Storing as string to match dummy data
    arrival_time        VARCHAR2(20) NOT NULL,
    aircraft_type       VARCHAR2(50),
    total_seats         NUMBER NOT NULL,
    available_seats     NUMBER NOT NULL,
    services            CLOB CHECK (services IS JSON),  -- JSON array of available services
    service_subtypes    CLOB CHECK (service_subtypes IS JSON),  -- JSON object with service subtypes
    seat_map            CLOB CHECK (seat_map IS JSON),  -- JSON array of seat objects
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_flights_date ON flights(flight_date);
CREATE INDEX idx_flights_route ON flights(route);