-- PASSENGERS TABLE
CREATE TABLE passengers (
    passenger_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id           NUMBER NOT NULL,
    name                VARCHAR2(100) NOT NULL,
    phone_number        VARCHAR2(20),
    address             VARCHAR2(300),
    passport_number     VARCHAR2(30),
    date_of_birth       DATE,
    origin              VARCHAR2(10) NOT NULL,
    destination         VARCHAR2(10) NOT NULL,
    services            CLOB CHECK (services IS JSON),  -- JSON array of services
    meal_type           VARCHAR2(50),
    meal_name           VARCHAR2(100),
    extra_baggage       NUMBER DEFAULT 0,
    shopping_items      CLOB CHECK (shopping_items IS JSON),  -- JSON array
    seat                VARCHAR2(10),
    checked_in          CHAR(1) DEFAULT 'N' CHECK (checked_in IN ('Y', 'N')),
    wheelchair          CHAR(1) DEFAULT 'N' CHECK (wheelchair IN ('Y', 'N')),
    infant              CHAR(1) DEFAULT 'N' CHECK (infant IN ('Y', 'N')),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_passengers_flight
        FOREIGN KEY (flight_id) REFERENCES flights(flight_id) ON DELETE CASCADE
);

CREATE INDEX idx_passengers_flight ON passengers(flight_id);
CREATE INDEX idx_passengers_name ON passengers(name);
CREATE INDEX idx_passengers_checkin ON passengers(checked_in);