-- TRAVEL HISTORY TABLE
CREATE TABLE travel_history (
    history_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id        NUMBER NOT NULL,
    flight_id           NUMBER NOT NULL,
    travel_date         DATE NOT NULL,
    origin              VARCHAR2(10) NOT NULL,
    destination         VARCHAR2(10) NOT NULL,
    seat                VARCHAR2(10),
    booking_reference   VARCHAR2(20) UNIQUE NOT NULL,
    fare_class          VARCHAR2(30),
    status              VARCHAR2(20) CHECK (status IN ('Completed', 'Checked-in', 'Cancelled', 'Pending', 'Booked')),
    distance_km         NUMBER,
    duration_min        NUMBER,
    notes               VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_history_passenger
        FOREIGN KEY (passenger_id) REFERENCES passengers(passenger_id) ON DELETE CASCADE,
    CONSTRAINT fk_history_flight
        FOREIGN KEY (flight_id) REFERENCES flights(flight_id) ON DELETE CASCADE
);

CREATE INDEX idx_history_passenger ON travel_history(passenger_id);
CREATE INDEX idx_history_flight ON travel_history(flight_id);
CREATE INDEX idx_history_date ON travel_history(travel_date);
CREATE INDEX idx_history_booking_ref ON travel_history(booking_reference);