-- ROUTES TABLE
CREATE TABLE routes (
    route_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_code          VARCHAR2(20) UNIQUE NOT NULL,  -- e.g., 'NYC-LON'
    departure_city      VARCHAR2(50) NOT NULL,
    departure_airport   VARCHAR2(10) NOT NULL,         -- IATA code
    arrival_city        VARCHAR2(50) NOT NULL,
    arrival_airport     VARCHAR2(10) NOT NULL,         -- IATA code
    distance_km         NUMBER,
    estimated_duration  NUMBER,                        -- minutes
    status              VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_routes_code ON routes(route_code);
CREATE INDEX idx_routes_departure ON routes(departure_airport);
CREATE INDEX idx_routes_arrival ON routes(arrival_airport);
CREATE INDEX idx_routes_status ON routes(status);